aliases: []
creation_timestamp: 1757682521368
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1757682521368
metrics: null
model_id: m-dff5297867de4f639dd014193dbaf999
name: fraud-detector
params: null
run_id: 07b3f051284341d2b37217430817202c
run_link: null
source: models:/m-dff5297867de4f639dd014193dbaf999
status: READY
status_message: null
storage_location: file:///Users/josiah/LocalProjects/fraud-detection-mlops/mlruns/902899545813332380/models/m-dff5297867de4f639dd014193dbaf999/artifacts
user_id: null
version: 4
