aliases: []
creation_timestamp: 1757681530511
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1757681530511
metrics: null
model_id: ''
name: fraud-detector
params: null
run_id: ''
run_link: ''
source: models:/fraud-detector/2
status: READY
status_message: null
storage_location: file:///Users/josiah/LocalProjects/fraud-detection-mlops/mlruns/902899545813332380/models/m-d6e17561796443a0a6e132075dc6be20/artifacts
user_id: null
version: 3
