aliases: []
creation_timestamp: 1757677781925
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1757677781925
metrics: null
model_id: m-d6e17561796443a0a6e132075dc6be20
name: fraud-detector
params: null
run_id: ''
run_link: ''
source: file:///Users/josiah/LocalProjects/fraud-detection-mlops/mlruns/902899545813332380/models/m-d6e17561796443a0a6e132075dc6be20/artifacts
status: READY
status_message: null
storage_location: file:///Users/josiah/LocalProjects/fraud-detection-mlops/mlruns/902899545813332380/models/m-d6e17561796443a0a6e132075dc6be20/artifacts
user_id: null
version: 2
