aliases: []
creation_timestamp: 1757514071104
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1757514071104
metrics: null
model_id: m-3e5f60a92a014d65b789aa33359fd700
name: fraud-detector
params: null
run_id: 7aa89c7001a0440ba636a40d9e7869a1
run_link: null
source: models:/m-3e5f60a92a014d65b789aa33359fd700
status: READY
status_message: null
storage_location: file:///Users/josiah/LocalProjects/fraud-detection-mlops/mlruns/902899545813332380/models/m-3e5f60a92a014d65b789aa33359fd700/artifacts
user_id: null
version: 1
