aliases: []
creation_timestamp: 1764929454960
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1764929454960
metrics: null
model_id: m-1963bd0723f648b697b234e6faf7f69d
name: fraud-detector
params: null
run_id: 1da52204fac7484a80a57568d2241155
run_link: null
source: models:/m-1963bd0723f648b697b234e6faf7f69d
status: READY
status_message: null
storage_location: file:///Users/josiah/LocalProjects/fraud-detection-mlops/mlruns/902899545813332380/models/m-1963bd0723f648b697b234e6faf7f69d/artifacts
user_id: null
version: 5
